<?php

namespace App\Controller;

use App\Controller\AppController;
use Google_Client;
use Google_Service_Drive;

/**
 * Files Controller
 *
 * @property \App\Model\Table\FilesTable $Files
 * @property  string $dir
 * @method \App\Model\Entity\File[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class  OauthController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->dir = ROOT . '\\';

    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */

    public function callback()
    {
        $dir = ROOT . '/';
        require_once ROOT .'/vendor' . '/autoload.php';

          echo ROOT.'vendor'.DS.'autoload.php<br>';

        $client = new Google_Client();
        $guzzleClient = new \GuzzleHttp\Client(array('curl' => array(CURLOPT_SSL_VERIFYPEER => false,),));
        $client->setHttpClient($guzzleClient);
        $client->setAuthConfigFile($this->dir . 'client_id.json');
        $client->setRedirectUri('http://' . $_SERVER['HTTP_HOST'] . '/cake/intranet/oauth/callback');
        $client->addScope(Google_Service_Drive::DRIVE);
        // $client->setRedirectUri('http://' . $_SERVER['HTTP_HOST'] . 'cake/intranet/oauth2callback.php');
        $client->setAccessType('offline');
        $client->setApprovalPrompt('force');

        $params = $this->request->getQueryParams('code');
         echo $this->dir . 'client_id.json';
        echo '<pre>';
         var_dump($client);
         var_dump($params);
        // exit;

        if (!isset($params['code'])) {
            echo 'code';
            $auth_url = $client->createAuthUrl();
            header('Location: ' . filter_var($auth_url, FILTER_SANITIZE_URL));
        } else {
            $params = $this->request->getQueryParams('code');
            echo 'code';
            echo $params['code'];
            $client->authenticate($params['code']);
            //$_SESSION['access_token'] = $client->getAccessToken();
            $access_token = $client->getAccessToken();
            //$access_token = $client->fetchAccessTokenWithAuthCode($_GET['code']);
            file_put_contents($dir . 'credentials.json', json_encode($access_token));

            $redirect_uri = 'http://' . $_SERVER['HTTP_HOST'] . '/cake/intranet/news/addNew';
            header('Location: ' . filter_var($redirect_uri, FILTER_SANITIZE_URL));
            exit;
            //$this->redirect(['controller' => 'news', 'action' => 'add']);
        }


    }

}
