<?php
/**
 * Created by PhpStorm.
 * User: dwere
 * Date: 1/31/2019
 * Time: 4:36 PM
 */

namespace App\Controller\Component;

use Cake\Controller\Component;
use Google_Client;
use Google_Service_Drive;

class GoogleDriveComponent extends Component
{

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->getService();
    }

    public function getService()
    {
        $dir = ROOT . '\\';
        $client = new Google_Client();
        $client->setAuthConfig($dir . 'client_id.json');
        $client->setApplicationName('Intranet');
        $client->addScope(Google_Service_Drive::DRIVE);
        if (file_exists($dir . "credentials.json")) {
            $access_token = (file_get_contents($dir . "credentials.json"));
            $client->setAccessToken($access_token);
            //Refresh the token if it's expired.
            if ($client->isAccessTokenExpired()) {
                $client->fetchAccessTokenWithRefreshToken($client->getRefreshToken());
                file_put_contents($dir . "credentials.json", json_encode($client->getAccessToken()));
            }
            return $client;

        } else {

            return null;
        }
    }
}
